<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKiCCeqT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKiCCeqT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKiCCeqT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKiCCeqT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKiCCeqT\App_KernelDevDebugContainer([
    'container.build_hash' => 'KiCCeqT',
    'container.build_id' => '0baec8b4',
    'container.build_time' => 1764248384,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKiCCeqT');
