<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKubzuKv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKubzuKv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKubzuKv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKubzuKv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKubzuKv\App_KernelDevDebugContainer([
    'container.build_hash' => 'KubzuKv',
    'container.build_id' => '45ec626c',
    'container.build_time' => 1764253869,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKubzuKv');
