<?php

namespace ContainerPEaa6mj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AmLOo1k.App\Controller\DashboardController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AmLOo1k.App\\Controller\\DashboardController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'request' => ['privates', '.errored.AWfueS8', NULL, 'Cannot determine controller argument for "App\\Controller\\DashboardController::edit()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'entityManager' => ['privates', '.errored.4.PTi_7', NULL, 'Cannot determine controller argument for "App\\Controller\\DashboardController::edit()": the $entityManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
        ], [
            'request' => '?',
            'security' => '?',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\DashboardController::edit()', $container);
    }
}
