<?php

namespace ContainerKubzuKv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\NewsService' shared autowired service.
     *
     * @return \App\Service\NewsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/NewsService.php';

        return $container->privates['App\\Service\\NewsService'] = new \App\Service\NewsService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
