<?php

namespace Container9CdKPax;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_HiYDQpvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.HiYDQpv' shared service.
     *
     * @return \App\Service\WeatherService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\DashboardController::index()": the $weatherService argument is type-hinted with the non-existent class or interface: "App\\Service\\WeatherService".');
    }
}
