<?php

namespace Container9CdKPax;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qB6mQOG.App\Controller\DashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qB6mQOG.App\\Controller\\DashboardController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'weatherService' => ['privates', '.errored.HiYDQpv', NULL, 'Cannot determine controller argument for "App\\Controller\\DashboardController::index()": the $weatherService argument is type-hinted with the non-existent class or interface: "App\\Service\\WeatherService".'],
            'newsService' => ['privates', 'App\\Service\\NewsService', 'getNewsServiceService', true],
            'financeService' => ['privates', '.errored.UcUR.yT', NULL, 'Cannot determine controller argument for "App\\Controller\\DashboardController::index()": the $financeService argument is type-hinted with the non-existent class or interface: "App\\Service\\FinanceService".'],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'weatherService' => '?',
            'newsService' => 'App\\Service\\NewsService',
            'financeService' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\DashboardController::index()', $container);
    }
}
